overrides:
  eslint@<9.26.0: '>=9.26.0'
  jsonpath@<1.2.0: '>=1.2.0'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  nth-check@<2.0.1: '>=2.0.1'
  postcss@<8.4.31: '>=8.4.31'
  qs@<6.14.1: '>=6.14.1'
  tar@<7.5.7: '>=7.5.7'
  tar@<=7.5.2: '>=7.5.3'
  tar@<=7.5.3: '>=7.5.4'
  webpack-dev-server@<=5.2.0: '>=5.2.1'
